title:            Ninja Tiny Kingdom
description:      Tiny Kingdom of Ninja, place we write and share our though and sweet home page on the World Wide Web.
url:              https://vnpt.ga/site
permalink:        /posts/:title
timezone:         Indian/Christmas
kramdown:
  hard_wrap: true
sass:
  sass_dir: assets
  style: :compressed
collections:
  notes:
    output: false
  pages:
    output: true
i18n:
  Travel: 旅行
  Animals: 動物
  Japan: 日本
  Books: 本
  Cook: 料理
  Plants: 植物
  24h: 時間
  Mails: 郵便物
  Friends: 仲間